name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      - uses: browser-actions/setup-chrome@v1
      - name: Run tests
        run: ./gradlew test -Dheadless=true
        continue-on-error: true

      - name: Upload report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-report
          path: build/reports/tests/test/